// Documents contain presentation structure and references to owned record fields.
// They never store another copy of a requirement, decision or task definition.
export const generatedNotice =
  '<!-- Generated by Archivarius; edit the project JSON, not this file. -->';

// Model prose is plain text, and every renderer neutralizes it the same way:
// only a character that can create Markdown structure is escaped, so a sentence
// stays readable. Escaping punctuation inside a sentence would not add safety.
export const escape = (value) =>
  String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replace(/([\\`*_[\]|~])/g, '\\$1')
    // Only a line that opens with Markdown structure can change the shape of the
    // document; punctuation inside a sentence must stay readable.
    .replace(/^(\s*)([#>+-]|\d+\.)/gm, '$1\\$2')
    // A line of "=" underlines the line above it into a heading.
    .replace(/^(\s*)(=+\s*)$/gm, '$1\\$2');
export const inline = (value) => escape(value).replace(/[\r\n]+/g, ' ');

export function documentReferences(document) {
  const found = [];
  const walk = (value, path) => {
    if (!value || typeof value !== 'object') return;
    if ('record' in value && 'field' in value) {
      found.push({
        record: value.record,
        field: value.field,
        index: value.index,
        as: value.as,
        path,
        validShape: Object.keys(value).every((key) =>
          ['record', 'field', 'index', 'as'].includes(key),
        ),
      });
      return;
    }
    for (const [key, part] of Object.entries(value))
      walk(part, path + '/' + key);
  };
  walk(document.blocks, 'blocks');
  walk(document.data, 'data');
  return found;
}

export function documentValue(records, reference) {
  const value = records.get(reference.record)?.[reference.field];
  const selected =
    reference.index === undefined ? value : value?.[reference.index];
  if (reference.as === 'labels') {
    const label = (key) => records.get(key)?.label ?? key;
    return Array.isArray(selected) ? selected.map(label) : label(selected);
  }
  return selected;
}

export function documentData(model, document) {
  const records = new Map(model.records.map((record) => [record.key, record]));
  const resolve = (value) => {
    if (!value || typeof value !== 'object') return value;
    if ('record' in value && 'field' in value)
      return documentValue(records, value);
    if (Array.isArray(value)) return value.map(resolve);
    return Object.fromEntries(
      Object.entries(value).map(([key, part]) => [key, resolve(part)]),
    );
  };
  return resolve(document.data);
}

export function documentSections(document, keys) {
  if (document.format !== 'markdown') return [];
  const references = (block) =>
    documentReferences({ blocks: [block] }).some((ref) => keys.has(ref.record));
  const chosen = new Set();
  const headings = document.blocks.flatMap((block, i) =>
    block.kind === 'heading' ? [i] : [],
  );
  for (const [i, block] of document.blocks.entries()) {
    if (!references(block)) continue;
    // A heading that names the subject owns its nested sections (e.g. a task's
    // changes, tests and exit). A criterion uses its nearest enclosing heading.
    const enclosing = headings.filter(
      (at) =>
        at <= i &&
        !headings.some(
          (end) =>
            end > at &&
            end <= i &&
            document.blocks[end].level <= document.blocks[at].level,
        ),
    );
    const start =
      enclosing.find((at) => references(document.blocks[at])) ??
      enclosing.at(-1) ??
      i;
    const level = document.blocks[start].level ?? 6;
    const end =
      headings.find((at) => at > start && document.blocks[at].level <= level) ??
      document.blocks.length;
    for (let at = start; at < end; at++) chosen.add(at);
  }
  if ((document.subjects || []).some((key) => keys.has(key)))
    document.blocks.forEach((_, i) => chosen.add(i));
  return [...chosen]
    .sort((a, b) => a - b)
    .map((index) => ({ index, block: document.blocks[index] }));
}

export function renderDocument(
  model,
  document,
  { notice = true, headingOffset = 0 } = {},
) {
  if (document.format === 'json')
    return JSON.stringify(documentData(model, document), null, 2) + '\n';
  const records = new Map(model.records.map((record) => [record.key, record]));
  // A block is authored presentation; a referenced record field is content, so it
  // is neutralized here, and flattened where the structure needs one line.
  const join = (parts, mark) =>
    parts
      .map((part) =>
        typeof part === 'string' ? part : mark(documentValue(records, part)),
      )
      .join('');
  const line = (parts) => join(parts, escape);
  const flat = (parts) => join(parts, inline);
  const blocks = document.blocks.map((block) => {
    switch (block.kind) {
      case 'heading':
        return (
          '#'.repeat(Math.min(6, block.level + headingOffset)) +
          ' ' +
          flat(block.content)
        );
      case 'paragraph':
        return block.lines.map(line).join('\n');
      case 'quote':
        return block.lines
          .map((parts) => '>' + (parts.length ? ' ' + line(parts) : ''))
          .join('\n');
      case 'comment':
        return '<!--' + block.lines.map(line).join('\n') + '-->';
      case 'anchor':
        return '<a id="' + block.id + '"></a>';
      case 'code': {
        const body = block.lines.join('\n');
        const fence = '`'.repeat(
          Math.max(3, ...[...body.matchAll(/`+/g)].map((m) => m[0].length + 1)),
        );
        return fence + block.language + '\n' + body + '\n' + fence;
      }
      case 'list':
        return block.items
          .map((lines, i) => {
            const prefix = block.ordered ? (block.start ?? 1) + i + '. ' : '- ';
            return (
              prefix + lines.map(line).join('\n' + ' '.repeat(prefix.length))
            );
          })
          .join('\n');
      case 'table': {
        const row = (cells) => '| ' + cells.map(flat).join(' | ') + ' |';
        return [
          row(block.header),
          row(block.header.map(() => ['---'])),
          ...block.rows.map(row),
        ].join('\n');
      }
      default:
        throw new Error('DOCUMENT_BLOCK:' + block.kind);
    }
  });
  return [...blocks, ...(notice ? [generatedNotice] : [])].join('\n\n') + '\n';
}

export function validateDocuments(model, issue) {
  const records = new Map(model.records.map((record) => [record.key, record]));
  const paths = new Set();
  for (const document of model.records.filter(
    (record) => record.type === 'document',
  )) {
    const path = document.path.toLowerCase();
    if (paths.has(path)) issue('DOCUMENT_PATH_DUPLICATE', document.key);
    paths.add(path);
    if (!path.endsWith(document.format === 'markdown' ? '.md' : '.json'))
      issue('DOCUMENT_FORMAT', document.key);
    for (const reference of documentReferences(document)) {
      const record = records.get(reference.record);
      const value = documentValue(records, reference);
      const jsonReference = reference.path.startsWith('data/');
      if (
        !record ||
        !Object.hasOwn(record, reference.field) ||
        record.type === 'document' ||
        value === undefined ||
        (!jsonReference && typeof value !== 'string') ||
        !reference.validShape ||
        (reference.as !== undefined && reference.as !== 'labels') ||
        ['key', 'type', 'basis', 'reconsideredBecause'].includes(
          reference.field,
        ) ||
        (reference.index !== undefined &&
          (!Number.isInteger(reference.index) ||
            reference.index < 0 ||
            !Array.isArray(record[reference.field])))
      )
        issue('DOCUMENT_REFERENCE', document.key, reference.path);
    }
    for (const block of document.blocks || [])
      if (
        block.kind === 'table' &&
        (!block.header.length ||
          block.rows.some((row) => row.length !== block.header.length))
      )
        issue('DOCUMENT_TABLE', document.key);
  }
}

/**
 * Presentation-only inline tokens. Only known document destinations become
 * navigation: HTML, images, external URLs and unknown paths remain plain text.
 * No token carries an href or executable markup.
 * @param {string} text
 * @param {any} document
 * @param {any[]} records
 * @returns {Array<{kind: string, text: string, record?: string, anchor?: string}>}
 */
export function documentInline(text, document, records) {
  const tokens = [];
  const pattern =
    /`([^`\n]+)`|\*\*([^*\n]+)\*\*|(?<!!)\[([^\]\n]+)\]\(([^\s)]+)\)/g;
  let end = 0;
  for (const match of text.matchAll(pattern)) {
    if (match.index > end)
      tokens.push({ kind: 'text', text: text.slice(end, match.index) });
    let token = { kind: 'text', text: match[0] };
    if (match[1]) token = { kind: 'code', text: match[1] };
    else if (match[2]) token = { kind: 'strong', text: match[2] };
    else if (!/^(?:[a-z][a-z\d+.-]*:|[\\/])/i.test(match[4])) {
      try {
        const base = new URL(document.path, 'https://document.invalid/');
        const target = new URL(match[4], base);
        const found = records.find(
          (record) =>
            record.type === 'document' &&
            new URL(record.path, 'https://document.invalid/').pathname ===
              target.pathname,
        );
        if (found && target.origin === base.origin && !target.search)
          token = {
            kind: 'reference',
            text: match[3],
            record: found.key,
            anchor: decodeURIComponent(target.hash.slice(1)),
          };
      } catch {
        /* An invalid destination remains literal text. */
      }
    }
    tokens.push(token);
    end = match.index + match[0].length;
  }
  if (end < text.length) tokens.push({ kind: 'text', text: text.slice(end) });
  return tokens;
}
