// Documents contain presentation structure and references to owned record fields.
// They never store another copy of a requirement, decision or task definition.
export const generatedNotice =
  '<!-- Generated by Archivarius; edit the project JSON, not this file. -->';

export function documentReferences(document) {
  const found = [];
  const walk = (value, path) => {
    if (!value || typeof value !== 'object') return;
    if ('record' in value && 'field' in value) {
      found.push({ ...value, path });
      return;
    }
    for (const [key, part] of Object.entries(value))
      walk(part, path + '/' + key);
  };
  walk(document.blocks, 'blocks');
  walk(document.data, 'data');
  return found;
}

export function documentValue(records, reference) {
  const value = records.get(reference.record)?.[reference.field];
  const selected =
    reference.index === undefined ? value : value?.[reference.index];
  if (reference.as === 'labels') {
    const label = (key) => records.get(key)?.label ?? key;
    return Array.isArray(selected) ? selected.map(label) : label(selected);
  }
  return selected;
}

export function documentData(model, document) {
  const records = new Map(model.records.map((record) => [record.key, record]));
  const resolve = (value) => {
    if (!value || typeof value !== 'object') return value;
    if ('record' in value && 'field' in value)
      return documentValue(records, value);
    if (Array.isArray(value)) return value.map(resolve);
    return Object.fromEntries(
      Object.entries(value).map(([key, part]) => [key, resolve(part)]),
    );
  };
  return resolve(document.data);
}

export function documentSections(document, keys) {
  if (document.format !== 'markdown') return [];
  const references = (block) =>
    documentReferences({ blocks: [block] }).some((ref) => keys.has(ref.record));
  const chosen = new Set();
  const headings = document.blocks.flatMap((block, i) =>
    block.kind === 'heading' ? [i] : [],
  );
  for (const [i, block] of document.blocks.entries()) {
    if (!references(block)) continue;
    // A heading that names the subject owns its nested sections (e.g. a task's
    // changes, tests and exit). A criterion uses its nearest enclosing heading.
    const enclosing = headings.filter(
      (at) =>
        at <= i &&
        !headings.some(
          (end) =>
            end > at &&
            end <= i &&
            document.blocks[end].level <= document.blocks[at].level,
        ),
    );
    const start =
      enclosing.find((at) => references(document.blocks[at])) ??
      enclosing.at(-1) ??
      i;
    const level = document.blocks[start].level ?? 6;
    const end =
      headings.find((at) => at > start && document.blocks[at].level <= level) ??
      document.blocks.length;
    for (let at = start; at < end; at++) chosen.add(at);
  }
  if ((document.subjects || []).some((key) => keys.has(key)))
    document.blocks.forEach((_, i) => chosen.add(i));
  return [...chosen]
    .sort((a, b) => a - b)
    .map((index) => ({ index, block: document.blocks[index] }));
}

export function renderDocument(
  model,
  document,
  { notice = true, headingOffset = 0 } = {},
) {
  if (document.format === 'json')
    return JSON.stringify(documentData(model, document), null, 2) + '\n';
  const records = new Map(model.records.map((record) => [record.key, record]));
  const line = (parts) =>
    parts
      .map((part) =>
        typeof part === 'string' ? part : documentValue(records, part),
      )
      .join('');
  const blocks = document.blocks.map((block) => {
    switch (block.kind) {
      case 'heading':
        return (
          '#'.repeat(Math.min(6, block.level + headingOffset)) +
          ' ' +
          line(block.content)
        );
      case 'paragraph':
        return block.lines.map(line).join('\n');
      case 'quote':
        return block.lines
          .map((parts) => '>' + (parts.length ? ' ' + line(parts) : ''))
          .join('\n');
      case 'comment':
        return '<!--' + block.lines.map(line).join('\n') + '-->';
      case 'anchor':
        return '<a id="' + block.id + '"></a>';
      case 'code': {
        const body = block.lines.join('\n');
        const fence = '`'.repeat(
          Math.max(3, ...[...body.matchAll(/`+/g)].map((m) => m[0].length + 1)),
        );
        return fence + block.language + '\n' + body + '\n' + fence;
      }
      case 'list':
        return block.items
          .map((lines, i) => {
            const prefix = block.ordered ? (block.start ?? 1) + i + '. ' : '- ';
            return (
              prefix + lines.map(line).join('\n' + ' '.repeat(prefix.length))
            );
          })
          .join('\n');
      case 'table': {
        const row = (cells) => '| ' + cells.map(line).join(' | ') + ' |';
        return [
          row(block.header),
          row(block.header.map(() => ['---'])),
          ...block.rows.map(row),
        ].join('\n');
      }
      default:
        throw new Error('DOCUMENT_BLOCK:' + block.kind);
    }
  });
  return [...blocks, ...(notice ? [generatedNotice] : [])].join('\n\n') + '\n';
}

export function validateDocuments(model, issue) {
  const records = new Map(model.records.map((record) => [record.key, record]));
  const paths = new Set();
  for (const document of model.records.filter(
    (record) => record.type === 'document',
  )) {
    const path = document.path.toLowerCase();
    if (paths.has(path)) issue('DOCUMENT_PATH_DUPLICATE', document.key);
    paths.add(path);
    if (!path.endsWith(document.format === 'markdown' ? '.md' : '.json'))
      issue('DOCUMENT_FORMAT', document.key);
    for (const reference of documentReferences(document)) {
      const record = records.get(reference.record);
      const value = documentValue(records, reference);
      const jsonReference = reference.path.startsWith('data/');
      if (
        !record ||
        !Object.hasOwn(record, reference.field) ||
        record.type === 'document' ||
        value === undefined ||
        (!jsonReference && typeof value !== 'string') ||
        Object.keys(reference).some(
          (key) => !['record', 'field', 'index', 'as', 'path'].includes(key),
        ) ||
        (reference.as !== undefined && reference.as !== 'labels') ||
        ['key', 'type', 'basis', 'reconsideredBecause'].includes(
          reference.field,
        ) ||
        (reference.index !== undefined &&
          (!Number.isInteger(reference.index) ||
            reference.index < 0 ||
            !Array.isArray(record[reference.field])))
      )
        issue('DOCUMENT_REFERENCE', document.key, reference.path);
    }
    for (const block of document.blocks || [])
      if (
        block.kind === 'table' &&
        (!block.header.length ||
          block.rows.some((row) => row.length !== block.header.length))
      )
        issue('DOCUMENT_TABLE', document.key);
  }
}
